### ISSUE TITLE
gRPC Stubs

### ISSUE THREAD

**Issue by dendisuhubdy** [mohammedaugie13/grpc-services#1]
Gimana perkembangannya bro?

**Comment by 0xdrmnhttn13** [comment]
bagus kok mas aku udh buat beberapa di komp, cuma untuk services to gk bisa return ke 2 value ya mas?

**Comment by dendisuhubdy** [comment]
` gk bisa return ke 2 value ya mas?` maksudnya gimana bro? Ada snippet code boleh paste disini?

**Comment by 0xdrmnhttn13** [comment]
`def f(x):
    X=[]
    Y=[]
    for i in range(len(x)):
        value=x[i]**2+2*x[i]*x[i]+5*x[i]
        val = x[i]**3 +2 * x[i] + 5
        X.append(value)
        Y.append(val)
    return X, Y`

aku mau buat service itu mas di grpc, nah di file grpc servernya bisa gk gini
`class Polynomial(polynomial_pb2_grpc.PolynomialServicer):
    def Solve(self, request, context):
        response=polynomial_pb2.variable()
        response.res_x, response.res_y=polynomial.f(request.x)
        return response.res_x, response.res_y`

dan grpc clientnya gini

`def run():
    with grpc.insecure_channel('localhost:50051') as channel:
        stub=polynomial_pb2_grpc.PolynomialStub(channel)
        for i in range(0, len(input)):
            request = polynomial_pb2.variable(x=input[i])
            response= stub.Solve(request)
            answer1.append(response.res_x)
            answer2.append(response.res_y)
        print(answer1)
        print(answer2)`

**Comment by dendisuhubdy** [comment]
#2
